### ISSUE TITLE
SDK calls os.exit() on incorrect SDK key

### ISSUE THREAD

**Issue by luvLinux** [featurehub-io/featurehub-go-sdk#12]
This is very dangerous because it crashses the hosting app

**Comment by chrusty** [comment]
Hi @luvLinux, thanks for your interest in the project!

This is actually an intentional design pattern, the assumption being that our users would want to know up-front if the FeatureHub client wasn't working (instead of silently failing for an unknown amount of time).

I think we'd probably want to keep this as the default behaviour, but we could potentially offer an override configuration (something like `FailWithoutExit()`. This would leave the decision up to the user, while maintaining the safe default.

What would the ideal solution look like to you?

**Comment by luvLinux** [comment]
hey @chrusty, thanks for replying so quickly. 

The issue with crashing the app is that the life of apps that use the SDK have to depend on FeatureHub server's configuration. Ideally it should not cascade the failure to the consuming apps. The solution, IMO, should be to allow raising error/panic to the host app and let it handle the error, whether it wants to exit or fallback.

This is an imagined scenario that may turn bad (I need to test it out): let say the host app has already been deployed, then someone remove the SDK key on our FeatureHub server, then the running app may just crash.

Right now, I'm trying to add "exitFunc" to `streamingclient.Config` so host apps can customize how to exit

**Comment by chrusty** [comment]
Hi @luvLinux don't sweat, I think I can implement something to help here. Watch this space!

**Comment by luvLinux** [comment]
is there any issue with providing `exitFunc` @chrusty? If not I'll open a PR

**Comment by chrusty** [comment]
Hey @luvLinux, sorry it has taken a while. I've had a bit of a busy week!

I've got a PR underway. It works, but I still need to provide a way for the user to define their own error handler (overriding the default one I've provided here).

Let me know if this looks like what you were thinking of.

**Comment by chrusty** [comment]
Sorry, this is the PR here: https://github.com/featurehub-io/featurehub-go-sdk/pull/13

**Comment by luvLinux** [comment]
yep, it's a bit like what I thought of. I didn't let the exitFunc handle the error though. Yours's a nice addition!

**Comment by chrusty** [comment]
OK great, check out [the new release](https://github.com/featurehub-io/featurehub-go-sdk/releases/tag/1.4.1) and let me know if you have any trouble with it.
